# Generated by Django 2.1.1 on 2018-09-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('label', models.CharField(max_length=150)),
                ('num', models.IntegerField()),
                ('sum', models.IntegerField()),
            ],
        ),
    ]
